version: "3"

services:

  guardian:
    build:
      context: ./guardian
      dockerfile: Dockerfile.dev
    ports:
      - "4000:3000"
    environment:
      - CONTAINER_API=http://container-port:3000
      - INSTANCES_PER_LAYER=16
      - MAP_HEIGHT=400
      - MAP_WIDTH=400
      - OVERLAP=10
    volumes:
      - "./guardian:/app"
    depends_on:
      - container-port
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1000M
        reservations:
          cpus: '0.50'
          memory: 250M

  container-port:
    build:
      context: ./container-port
      dockerfile: Dockerfile.dev
    ports:
      - "3000"
    volumes:
      - "./container-port:/app"
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 250M
        reservations:
          cpus: '0.25'
          memory: 125M

  charge:
    build:
      context: ./charge
      dockerfile: Dockerfile.dev
    ports:
      - "3000"
    volumes:
      - "./charge:/app"
    environment:
      - GUARDIAN_API=http://guardian:3000
    depends_on:
      - guardian
    deploy:
      mode: replicated
      replicas: 32
      resources:
        limits:
          cpus: '0.50'
          memory: 200M
        reservations:
          cpus: '0.25'
          memory: 100M
