FROM oven/bun:0.5.8

WORKDIR /app

# Install dependencies
COPY package.json bun.lockb ./
RUN bun install

# Copy source code
COPY . .

# Expose port
EXPOSE 3000

# Start Dev mode
CMD ["bun", "run", "dev"]